apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dormouse-python 
  janus-idp.io/tekton: dormouse-python
  backstage.io/kubernetes-id: dormouse-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dormouse-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  